<?php           

/*------------------------------------------------------------------------
# SM CoolAccordion - Version 1.0
# Copyright (C) 2009-2011 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.smartaddons.com
-------------------------------------------------------------------------*/
           
?>
<?php
 $divid = rand().time();
 $smarthelper= Mage::helper('coolaccordion/utils');
 $items = $this->getProducts();
 $config = $this->getConfigObject();
 ?>
<?php if(count($items)>0):?>
	<?php echo $this->getScriptTags(); ?>
	<?php echo $this->getCssHead(); ?>	
		<?php
		$mod_width = intval($config['module_width']);
		$mod_style_width = $mod_width>0 ? "style=\"width:{$mod_width}px;\"" : "";
		?>
		<?php if (!empty($config['title'])): ?>
		<div class="block-title" style="font-size: 16px; font-weight: bold;"><?php echo $config['title']; ?></div>
		<?php endif; ?>
		<!--Intro Text-->
		<?php if($config['pretext']): ?>
		<div style="text-align:left;">
			<div class="yt_introtext" <?php echo $mod_style_width; ?> ><?php  echo $config['pretext'];?></div>
		</div>
		<br/>
		<?php endif;?>
		<div class="sm_coolaccordion">
			<div class="yt_section_inner">
					<?php require $config['theme'].'.phtml' ?>
			</div>
		</div>
		<?php 
			$script ='//<CDATA[[ ';
			if($config['theme']=='theme1'){
				$script	= '$jsmart(document).ready(function() {
				  
								$jsmart("#theme1_accordion_'.$divid.'").hrzAccordion({
									containerClass     : "theme1_cc_container",
									listItemClass      : "theme1_cc_listItem",					
									contentWrapper     : "theme1_cc_contentWrapper",
									contentInnerWrapper: "theme1_cc_contentInnerWrapper",
									handleClass        : "theme1_cc_handle",
									handleClassOver    : "theme1_cc_handleOver",
									handleClassSelected: "theme1_cc_handleSelected",
									moduleHeight       : '.$config['module_height'].'
								});
							 });
							 ';
			}
			if($config['theme']=='theme4'){
				$script	= '$jsmart(document).ready(function() {
				
								$jsmart("#theme4_accordion_'.$divid.'").hrzAccordion({
									containerClass     : "theme4_cc_container",
									listItemClass      : "theme4_cc_listItem",					
									contentWrapper     : "theme4_cc_contentWrapper",
									contentInnerWrapper: "theme4_cc_contentInnerWrapper",
									handleClass        : "theme4_cc_handle",
									handleClassOver    : "theme4_cc_handleOver",
									handleClassSelected: "theme4_cc_handleSelected",
									eventTrigger	   : "mouseover",
									moduleHeight       : '.$config['module_height'].'
								});
							 });
							 ';
			}
			if($config['theme']=='theme2'){
				$script	= '$jsmart(document).ready(function(){$jsmart("#content_cool_theme2_'.$divid.'").ytAccordion({';
				$script	.= 'firstSlide : 1,';
				$script	.= 'containerWidth :'.$config['module_width'].', ';
				$script	.= 'containerHeight :'.$config['module_height'].' ';
				$script	.= '})});';
			}
			if($config['theme']=='theme3'){
				$script	= '$jsmart(document).ready(function(){$jsmart("#content_cool_theme3_'.$divid.'").ytAccordion({';
				$script	.= 'firstSlide : 1,';
				$script	.= 'containerWidth :'.$config['module_width'].', ';
				$script	.= 'containerHeight :'.$config['module_height'].', ';
				$script	.= 'headerWidth :21 ';
				$script	.= '})});';
			}
			$script .= '		//]]>';
			echo '<script language="javascript">'.$script.'</script>';
		?>
<!--End Module-->
<?php else: ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php endif; ?>	
<?php if($config['posttext']): ?>
<br/>
<div style="text-align:left">
	<div class="yt_footertext" <?php echo $mod_style_width; ?> ><p><?php  echo $config['posttext'];?></p></div>
</div>
<?php endif;?>