<?php
/*------------------------------------------------------------------------
# SM CoolAccordion - Version 1.0
# Copyright (C) 2009-2011 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.smartaddons.com
-------------------------------------------------------------------------*/
?>
<div class="content_cool_theme3" id="content_cool_theme3_<?php echo $divid;?>" >
		<ol>
			<?php 
			foreach ($items as $item){
			?>
				<li class="clearfix">
					<div  class="accTab" style="height:<?php echo $config['module_height']; ?>px;">
						<div class="divTab">
							<div class="divTabInner" >
								<img src="<?php echo $this->getSkinUrl('smartaddons/coolaccordion/images/theme3-tab-selected-vertical.png');?>" class="img_tab_selected" style="height:<?php echo $config['module_height'];?>px;" alt="" />
								<img src="<?php echo $this->getSkinUrl('smartaddons/coolaccordion/images/theme3-tab-vertical.png');?>" class="img_tab" style="height:<?php echo $config['module_height'];?>px;" alt="" />
								<div class="theme3_div_title" <?php if (!empty($config['product_title_color'])) echo 'style="color:'.$config['product_title_color'].'; width: '.$config['module_height'].'px;"'; else echo 'style="width: '.$config['module_height'].'px;"'; ?> ><?php echo $item['sub_title'];?></div>
							</div>
						</div>
					</div>
						<div <?php if (isset($config['product_image_background']) && !empty($config['product_image_background'])) echo 'style="background: '.$config['product_image_background']. ';"'; ?> >
						<?php if ($config['product_image_disp']) { ?>
							<?php if ($config['product_image_linkable']==0){ ?>
								<img class="theme3_img_background" src="<?php echo $item['thumb'];?>" alt="" />
							<?php } else { ?>
								<img class="theme3_img_background_with_link" src="<?php echo $item['thumb'];?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?> alt="" />
							<?php } ?>
						<?php } ?>
						
						<?php if ($config['product_description_disp'] == 1 || $config['product_title_disp']==1) { ?>
							<div class="divDescriptionBg" <?php if (isset($config['product_description_opacity']) && !empty($config['product_description_opacity'])) echo 'style="opacity: '.$config['product_description_opacity']. '; filter: alpha(opacity: '.($config['product_description_opacity']*100).');"'; ?> ></div>
							<div class="divDescriptionContent" <?php if (!empty($config['product_description_color'])) echo 'style="color:'.$config['product_description_color'].';"';?> >
								<?php if ($config['product_title_disp']==1){?>
								<div class="divTitle">
									<?php
										if ($config['product_title_linkable']==1){	?>
											<a href="<?php echo $item['link']?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?>><?php echo $item['sub_title']?></a>
									<?php	}
										else
											echo $item['sub_title'];
									?>
								</div>
								<?php } ?>
								<div class="divInfoText">
									<?php if ($config['product_description_disp']==1){
											echo $item['sub_content'];
											echo '<hr class="theme3_hr" />';
										?>
											<div class="theme3_acc_footer">
												<div class="theme3_price">
													<?php echo $item['price'];?>
												</div>
												<div class="theme3_readmore">
										<?php
											if ($config['product_details_page_link_disp']==1){	?>
												<a href="<?php echo $item['link']?>" <?php echo $smarthelper->getTargetAttr($config['product_links_target']); ?>><?php echo $config['product_details_page_link_text']?></a>
										<?php	}	?>
												</div>
											</div>
									<?php } ?>
								</div>
							</div>
						<?php } ?>
						</div>
				</li>
			<?php } ?>
		</ol>
</div>
